module Sigaffold
  VERSION: String

  module AppDetector
    def self.detect: (?String path) -> (:gem | :rails | :other)
  end

  class RbsIntroducer
    type confirmer = ^(String) -> String

    def initialize: (?path: String, ?confirmer: confirmer) -> void
    def run: () -> void
  end
end
